changed order

diff --git a/.github/workflows/templates-e2e.yaml b/.github/workflows/templates-e2e.yaml
--- a/.github/workflows/templates-e2e.yaml
+++ b/.github/workflows/templates-e2e.yaml
@@ -75,7 +75,26 @@ jobs:
         curl -X POST "http://localhost:9080/api/catalog/locations" -H "Authorization: Bearer $BACKEND_TOKEN" -H 'Content-Type: application/json' -d '{"type":"url","target":"https://github.com/ElaiShalevRH/workflow-software-templates/blob/main/scaffolder-templates/github-workflows/basic-workflow/template.yaml"}'
 
 
+    - name: Run Advanced Template
+      run: | 
+        TASK_ID2=$(curl -X POST "$BACKSTAGE_URL/api/scaffolder/v2/tasks" -H "Authorization: Bearer $BACKEND_TOKEN" -H "Content-Type: application/json" -d '{"templateRef":"template:default/advanced-workflow-bootstrap","values":{"owner":"user:guest","orgName":"test-workflows","repoName":"test-repo","description":"This is a Test Repository","workflowId":"test","CI":"tekton_argocd","argocdNamespace":"argocd","infrastructureWorkflowId":"test","namespace":"sonataflow-operator-system","persistencePSQLDatabaseName":"sonataflow","persistencePSQLPasswordKey":"$PSQL_SECRET","persistencePSQLSecretName":"sonataflow-psql-postgresql","persistencePSQLServiceName":"orchestrator-postgresql","persistencePSQLServiceNamespace":"default","persistencePSQLServicePort":5432,"persistencePSQLUserKey":"$PSQL_SECRET","quayConfig":"Use Existing Repository","quayOrgName":"testing-eshalev","quayRepoName":"cray","system":"Guest"}}' | jq .id | tr -d '"')
+        echo "TASK_ID2=$TASK_ID2" >> $GITHUB_ENV
+    
+    - name: Validate Advanced Template Successs
+      run: | 
+        sleep 20
+        RESULT=$(curl -X GET "$BACKSTAGE_URL/api/scaffolder/v2/tasks/$TASK_ID2" -H "Authorization: Bearer $BACKEND_TOKEN" | jq .status)
+        echo "NOW"
+        echo $RESULT
+        if [ "$RESULT" = "failed" ]; then 
+          echo "The Basic template launched but failed to complete."
+          exit 1
+        fi
 
+        if [ "$RESULT" = "success" ]; then 
+          echo "The Basic template was executed successfully."
+        fi
+        
         
     - name: Run Basic Template
       run: | 
@@ -99,27 +118,6 @@ jobs:
           echo "The Basic template was executed successfully."
         fi
 
-
-    - name: Run Advanced Template
-      run: | 
-        TASK_ID2=$(curl -X POST "$BACKSTAGE_URL/api/scaffolder/v2/tasks" -H "Authorization: Bearer $BACKEND_TOKEN" -H "Content-Type: application/json" -d '{"templateRef":"template:default/advanced-workflow-bootstrap","values":{"owner":"user:guest","orgName":"test-workflows","repoName":"test-repo","description":"This is a Test Repository","workflowId":"test","CI":"tekton_argocd","argocdNamespace":"argocd","infrastructureWorkflowId":"test","namespace":"sonataflow-operator-system","persistencePSQLDatabaseName":"sonataflow","persistencePSQLPasswordKey":"$PSQL_SECRET","persistencePSQLSecretName":"sonataflow-psql-postgresql","persistencePSQLServiceName":"orchestrator-postgresql","persistencePSQLServiceNamespace":"default","persistencePSQLServicePort":5432,"persistencePSQLUserKey":"$PSQL_SECRET","quayConfig":"Use Existing Repository","quayOrgName":"testing-eshalev","quayRepoName":"cray","system":"Guest"}}' | jq .id | tr -d '"')
-        echo "TASK_ID2=$TASK_ID2" >> $GITHUB_ENV
-    
-    - name: Validate Advanced Template Successs
-      run: | 
-        sleep 20
-        RESULT=$(curl -X GET "$BACKSTAGE_URL/api/scaffolder/v2/tasks/$TASK_ID2" -H "Authorization: Bearer $BACKEND_TOKEN" | jq .status)
-        echo "NOW"
-        echo $RESULT
-        if [ "$RESULT" = "failed" ]; then 
-          echo "The Basic template launched but failed to complete."
-          exit 1
-        fi
-
-        if [ "$RESULT" = "success" ]; then 
-          echo "The Basic template was executed successfully."
-        fi
-        
     
     - name: Cleanup
       run: |
